# Generated by Django 4.2.5 on 2024-02-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_buy',
            name='quantity',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='product_buy',
            name='size',
            field=models.CharField(default='M', max_length=100),
        ),
    ]
