# Generated by Django 4.2.5 on 2024-02-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_buy_quantity_product_buy_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_buy',
            name='is_cash_on_delevery',
            field=models.BooleanField(default=False),
        ),
    ]
