# Generated by Django 4.2.5 on 2024-02-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_pro_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_img',
            field=models.ImageField(upload_to='amit'),
        ),
    ]
