# Generated by Django 4.2.5 on 2024-02-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecart',
            name='size',
            field=models.CharField(default='M', max_length=100),
        ),
        migrations.AlterField(
            model_name='ecart',
            name='quantity',
            field=models.IntegerField(default='1'),
        ),
    ]
