# Generated by Django 4.2.5 on 2024-02-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0003_alter_ecart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecart',
            name='quantity',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
