# Generated by Django 4.2.5 on 2024-02-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0004_alter_ecart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ecart',
            name='size',
        ),
    ]
