# Generated by Django 4.2.5 on 2024-02-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0006_ecart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecart',
            name='quantity',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
