# Generated by Django 4.2.5 on 2024-02-25 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0009_product_order_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_order_buy',
            name='product',
        ),
    ]
