# Generated by Django 4.2.5 on 2024-02-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='pro_pic',
            field=models.ImageField(upload_to='amit/'),
        ),
    ]
