# Generated by Django 4.2.5 on 2024-02-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_profile_pro_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='pro_pic',
            field=models.ImageField(upload_to='profiles'),
        ),
    ]
