# Generated by Django 4.2.5 on 2024-02-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_ecom_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ecom_User',
        ),
    ]
